import { PrismaClient } from '@prisma/client'

export const prisma = new PrismaClient()

const demoFirstName = process.env.DEMO_USER_FIRST_NAME ?? 'Mariana'
const demoLastName = process.env.DEMO_USER_LAST_NAME ?? 'Ortega'

export const DEMO_USER_DATA = {
  email: process.env.DEMO_USER_EMAIL ?? 'mariana.ortega@ejemplo.dev',
  username: process.env.DEMO_USER_USERNAME ?? 'marianaortega',
  firstName: demoFirstName,
  lastName: demoLastName,
  displayName: `${demoFirstName} ${demoLastName}`,
  avatar:
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  bio: 'Desarrolladora full-stack; me interesa ritmo circadiano y trabajo enfocado.',
  timezone: process.env.DEMO_USER_TIMEZONE ?? 'America/Mexico_City',
  language: process.env.DEMO_USER_LANGUAGE ?? 'es',
  password: process.env.DEMO_USER_PASSWORD ?? 'Demo123!',
}

/** Tareas de ejemplo con tono cotidiano (trabajo remoto + vida real). */
export const DEMO_ACTIVITIES = [
  {
    title: 'Responder correos y revisar el tablero de sprint',
    description:
      'Priorizar tickets, contestar bloqueos del equipo y dejar listo lo urgente antes del stand-up.',
    type: 'work' as const,
    duration: 45,
    priority: 'high' as const,
    tags: ['email', 'planning'],
    hoursFromNow: 1,
  },
  {
    title: 'Preparar demo interna del módulo de sesiones',
    description:
      'Ensayar flujo feliz, anotar edge cases y dejar capturas para el changelog.',
    type: 'work' as const,
    duration: 90,
    priority: 'high' as const,
    tags: ['demo', 'qa'],
    hoursFromNow: 4,
  },
  {
    title: 'Curso en línea: tests de integración con Vitest',
    description: 'Terminar el capítulo de mocks de DB y hacer los ejercicios del repo.',
    type: 'learning' as const,
    duration: 75,
    priority: 'medium' as const,
    tags: ['vitest', 'backend'],
    hoursFromNow: 8,
  },
  {
    title: 'Salir a caminar y estirar espalda',
    description: '25–30 minutos sin pantalla; hidratarse al volver.',
    type: 'health' as const,
    duration: 35,
    priority: 'medium' as const,
    tags: ['movimiento', 'descanso'],
    hoursFromNow: 24,
  },
  {
    title: 'Bocetos de UI para el calendario semanal',
    description:
      'Explorar layout mobile-first y estados vacíos; sin pixel-perfect todavía.',
    type: 'creative' as const,
    duration: 60,
    priority: 'medium' as const,
    tags: ['figma', 'ux'],
    hoursFromNow: 28,
  },
  {
    title: 'Revisión 1:1 con tu lead',
    description:
      'Feedback del trimestre, prioridades del próximo mes y dudas de carrera.',
    type: 'personal' as const,
    duration: 50,
    priority: 'high' as const,
    tags: ['1:1', 'carrera'],
    hoursFromNow: 72,
  },
]

export const USER_PREFERENCES = {
  notificationSettings: {
    email: true,
    push: true,
    reminders: true,
  },
  privacySettings: {
    profileVisibility: 'private' as const,
    activityVisibility: 'private' as const,
  },
  accessibilitySettings: {
    theme: 'dark' as const,
    fontSize: 'medium' as const,
    highContrast: false,
  },
}

/** Canonical circadian catalog — must match Prisma `CircadianPhaseType` (seed + runtime). */
export const CIRCADIAN_PHASES = [
  {
    type: 'slow_activation' as const,
    category: 'activation' as const,
    priority: 'low' as const,
    startHour: 5,
    endHour: 7,
    duration: 120,
    name: 'Slow Activation Phase',
    keyword: 'Calm',
    description:
      'Sleep inertia suppresses throughput and reaction quality right after waking, while the cortisol awakening response (CAR) is still ascending—output is low because the brain has not yet cleared inertia, not because effort is missing.',
    idealFor:
      'Morning meditation, gratitude journaling, light stretching, hydration, loose day planning',
    color: '#fde047',
    icon: 'coffee',
    emoji: '🟡',
    isPremium: false,
    isIntuitive: true,
    scientificReferences: ['PMC6710480', 'PMC9669756'],
    evidenceLevel: 'high',
    sortOrder: 1,
  },
  {
    type: 'morning_focus_peak' as const,
    category: 'performance' as const,
    priority: 'critical' as const,
    startHour: 7,
    endHour: 10,
    duration: 180,
    name: 'Morning Focus Peak',
    keyword: 'Focus',
    description:
      'CAR typically peaks about 30–45 minutes after waking, then subsides as alertness, working memory, and sustained attention improve—this is the best default window for structured study and learning new material.',
    idealFor: 'Technical reading, structured study, note-taking, learning new concepts',
    color: '#4ade80',
    icon: 'sun',
    emoji: '🟢',
    isPremium: true,
    isIntuitive: false,
    scientificReferences: ['PMC9669756', 'PMC10683050', '10.1007/s11325-023-02895-0'],
    evidenceLevel: 'high',
    sortOrder: 2,
  },
  {
    type: 'cognitive_peak' as const,
    category: 'performance' as const,
    priority: 'critical' as const,
    startHour: 10,
    endHour: 13,
    duration: 180,
    name: 'Cognitive Performance Peak',
    keyword: 'Peak',
    description:
      'Core body temperature approaches its circadian maximum, tracking with peak processing speed, working memory, and executive control—reserve this block for demanding analytical work rather than light admin.',
    idealFor: 'Programming, complex problem-solving, deep work, high-stakes decisions',
    color: '#60a5fa',
    icon: 'activity',
    emoji: '🔵',
    isPremium: true,
    isIntuitive: false,
    scientificReferences: ['PMC10683050', '10.1007/s11325-023-02895-0', 'PMC6430172'],
    evidenceLevel: 'high',
    sortOrder: 3,
  },
  {
    type: 'second_productivity' as const,
    category: 'performance' as const,
    priority: 'medium' as const,
    startHour: 13,
    endHour: 15,
    duration: 120,
    name: 'Second Productivity Peak',
    keyword: 'Recover',
    description:
      'The post-lunch circasemidian dip slows alertness and reaction time—favor structured, low-stakes tasks instead of peak-demand work; a 10–20 minute nap can blunt the dip before the afternoon rebound.',
    idealFor: 'Email, admin tasks, structured reviews, short nap (10–20 min)',
    color: '#38bdf8',
    icon: 'repeat',
    emoji: '🔵',
    isPremium: true,
    isIntuitive: false,
    scientificReferences: ['PMC2647793', 'PMC6430172'],
    evidenceLevel: 'medium',
    sortOrder: 4,
  },
  {
    type: 'creative_window' as const,
    category: 'creative' as const,
    priority: 'medium' as const,
    startHour: 15,
    endHour: 18,
    duration: 180,
    name: 'Creative/Verbal Window',
    keyword: 'Create',
    description:
      'Afternoon body-temperature rhythm and a looser analytical grip can reduce prefrontal inhibition, supporting remote associations and verbal output—consistent with Wieth & Zacks (2011) on insight timing when inhibitory control is relaxed.',
    idealFor: 'Writing, design, brainstorming, language output, creative ideation',
    color: '#a78bfa',
    icon: 'pen-tool',
    emoji: '🟣',
    isPremium: false,
    isIntuitive: true,
    scientificReferences: ['10.5465/amj.2019.0020', 'PMID:27791394', 'PMC6430172'],
    evidenceLevel: 'medium',
    sortOrder: 5,
  },
  {
    type: 'transition' as const,
    category: 'reflection' as const,
    priority: 'medium' as const,
    startHour: 18,
    endHour: 20,
    duration: 120,
    name: 'Transition Phase',
    keyword: 'Reflect',
    description:
      'Core temperature drifts down from the daytime peak and energy shifts from high output toward consolidation—encode the day with review, journaling, and light planning instead of brand-new heavy lifting.',
    idealFor:
      'Review of the day’s work, journaling, spaced-repetition review, light planning',
    color: '#fdba74',
    icon: 'book-open',
    emoji: '🟠',
    isPremium: false,
    isIntuitive: true,
    scientificReferences: ['PMC6430172', 'PMC10683050'],
    evidenceLevel: 'medium',
    sortOrder: 6,
  },
  {
    type: 'introspective' as const,
    category: 'reflection' as const,
    priority: 'low' as const,
    startHour: 20,
    endHour: 22,
    duration: 120,
    name: 'Introspective Phase',
    keyword: 'Plan',
    description:
      'Dim-light melatonin onset (often ~2 hours before habitual sleep) pulls physiology away from external vigilance toward inward processing and autobiographical access—good for reflection and next-day setup without bright screens.',
    idealFor:
      'Slow reading, visualization, planning tomorrow, personal reflection, gratitude review',
    color: '#fde047',
    icon: 'moon',
    emoji: '🟡',
    isPremium: false,
    isIntuitive: true,
    scientificReferences: ['PMC10683050', 'PMC9669756'],
    evidenceLevel: 'medium',
    sortOrder: 7,
  },
  {
    type: 'sleep_preparation' as const,
    category: 'rest' as const,
    priority: 'low' as const,
    startHour: 22,
    endHour: 5,
    duration: 420,
    name: 'Sleep Preparation',
    keyword: 'Sleep',
    description:
      'Melatonin signaling, core body temperature near its circadian nadir, and high adenosine sleep pressure converge to favor sleep, not work; bright screens and stimulating content can suppress melatonin—prioritize darkness, coolness, and routine.',
    idealFor:
      'Sleep hygiene routine, dark/cool environment, avoid screens and stimulating content',
    color: '#a3a3a3',
    icon: 'bed',
    emoji: '⚫',
    isPremium: false,
    isIntuitive: false,
    scientificReferences: ['PMC9669756', 'PMC6710480'],
    evidenceLevel: 'high',
    sortOrder: 8,
  },
]
